export const elements = {
    homePageContent:document.querySelector('.content'),
    searchPageContent:document.querySelector('.search_container'),
    searchDetailsContent: document.querySelector('.details_container'),
    seatsContent: document.querySelector('.seats_container'),
    peopleContent: document.querySelector('.person-list'),
    reservationContent: document.querySelector('.reservation_container'),
    allReservationsContent: document.querySelector('.reservations_content'),
    reservationContainer: document.querySelector('.container_forms'),
    navigationButtonSignup: document.getElementById('nb_0'),
    navigationButtonLogin: document.getElementById('nb_1'),
    navigationButtonLogout: document.getElementById('nb_logout'),
    navigationButtonLoginWorker: document.getElementById('nb_2'),
    navigationButtonLogoutWorker: document.getElementById('nb_logout_worker'),
    navigationButtonMyFlights: document.getElementById('nb_3'),
    logInForm: document.querySelector('.login_panel'),
    signUpForm: document.querySelector('.signup_panel'),
    logInWorkerForm: document.querySelector('.login_panel_worker'),
    logInSubmit: document.querySelector('.login_submit_button'),
    logInWorkerSubmit: document.querySelector('.login_worker_submit_button'),
    signUpSubmit: document.querySelector('.signup_submit_button'),
    searchPanel: document.querySelector('.flight-search__panel'),
    listPanel: document.querySelector('.flight-search__panel__toggler'),
    listPanelOrigin: document.querySelector('.flight-search-origin'),
    listPanelDestination: document.querySelector('.flight-search-destination'),
    originList: document.querySelector('.flight-search__panel__toggler__origins'),
    destinationList: document.querySelector('.flight-search__panel__toggler__destinations'),
    originListElement: document.querySelector('.flight-search__panel__toggler__origins__element'),
    destinationListElement: document.querySelector('.flight-search__panel__toggler__destinations__element'),
    originListButton: document.querySelector('.btn-flight-search__origin'),
    destinationListButton: document.querySelector('.btn-flight-search__destination'),
    decreasePeopleButton: document.querySelector('.btn-decrease'),
    increasePeopleButton: document.querySelector('.btn-increase'),
    numberOfPeople:  document.querySelector('.flight-search__panel__content__person_number'),
    searchSubmitButton: document.querySelector('.flight-search-submit'),
    monthSearchList: document.querySelector('.flight-search-when__month'),
    yearSearchList: document.querySelector('.flight-search-when__year'),
    dayButtons: document.querySelectorAll('.day'),
    seatButtons: document.querySelectorAll('.seat'),
    seatSubmitbutton: document.querySelector('.person_seat__submit'),
    reservationSum: document.querySelector('.reservation_sum'),
    reservationSubmit: document.querySelector('.reservation__submit')

}